export const patientData = [
  {
    patient: {
      image: "/assets/images/Pedro.png",
      name: "Pedro Becker",
      clinic: "Smiling Teeth Clinic",
    },
    planType: "Payment Plan",
    paymentDate: "May 1,2022",
    balance: { amount: "545.00", installments: "4" },
    paymentAmount: { amount: "25.00", financed: "1855.00" },
    status: "Active",
  },
  {
    patient: {
      image: "/assets/images/Pedro.png",
      name: "Pedro Becker",
      clinic: "Smiling Teeth Clinic",
    },
    planType: "Payment Plan",
    paymentDate: "May 1,2022",
    balance: { amount: "545.00", installments: "4" },
    paymentAmount: { amount: "25.00", financed: "1855.00" },
    status: "Active",
  },
  {
    patient: {
      image: "/assets/images/Pedro.png",
      name: "Pedro Becker",
      clinic: "Smiling Teeth Clinic",
    },
    planType: "Payment Plan",
    paymentDate: "May 1,2022",
    balance: { amount: "545.00", installments: "4" },
    paymentAmount: { amount: "25.00", financed: "1855.00" },
    status: "Past Due",
  },
  {
    patient: {
      image: "/assets/images/Pedro.png",
      name: "Pedro Becker",
      clinic: "Smiling Teeth Clinic",
    },
    planType: "Payment Plan",
    paymentDate: "May 1,2022",
    balance: { amount: "545.00", installments: "4" },
    paymentAmount: { amount: "25.00", financed: "1855.00" },
    status: "Pending",
  },
  {
    patient: {
      image: "/assets/images/Pedro.png",
      name: "Pedro Becker",
      clinic: "Smiling Teeth Clinic",
    },
    planType: "Membership",
    paymentDate: "May 1,2022",
    balance: { amount: "545.00", installments: "4" },
    paymentAmount: { amount: "25.00", financed: "1855.00" },
    status: "Pending",
  },
  {
    patient: {
      image: "/assets/images/Pedro.png",
      name: "Pedro Becker",
      clinic: "Smiling Teeth Clinic",
    },
    planType: "Membership",
    paymentDate: "May 1,2022",
    balance: { amount: "545.00", installments: "4" },
    paymentAmount: { amount: "25.00", financed: "1855.00" },
    status: "Active",
  },
  {
    patient: {
      image: "/assets/images/Pedro.png",
      name: "Pedro Becker",
      clinic: "Smiling Teeth Clinic",
    },
    planType: "Membership",
    paymentDate: "May 1,2022",
    balance: { amount: "545.00", installments: "4" },
    paymentAmount: { amount: "25.00", financed: "1855.00" },
    status: "Active",
  },
  {
    patient: {
      image: "/assets/images/Pedro.png",
      name: "Pedro Becker",
      clinic: "Smiling Teeth Clinic",
    },
    planType: "Membership",
    paymentDate: "May 1,2022",
    balance: { amount: "545.00", installments: "4" },
    paymentAmount: { amount: "25.00", financed: "1855.00" },
    status: "Active",
  },
  {
    patient: {
      image: "/assets/images/Pedro.png",
      name: "Pedro Becker",
      clinic: "Smiling Teeth Clinic",
    },
    planType: "Payment Plan",
    paymentDate: "May 1,2022",
    balance: { amount: "545.00", installments: "4" },
    paymentAmount: { amount: "25.00", financed: "1855.00" },
    status: "Active",
  },
  {
    patient: {
      image: "/assets/images/Pedro.png",
      name: "Pedro Becker",
      clinic: "Smiling Teeth Clinic",
    },
    planType: "Payment Plan",
    paymentDate: "May 1,2022",
    balance: { amount: "545.00", installments: "4" },
    paymentAmount: { amount: "25.00", financed: "1855.00" },
    status: "Active",
  },
  {
    patient: {
      image: "/assets/images/Pedro.png",
      name: "Pedro Becker",
      clinic: "Smiling Teeth Clinic",
    },
    planType: "Payment Plan",
    paymentDate: "May 1,2022",
    balance: { amount: "545.00", installments: "4" },
    paymentAmount: { amount: "25.00", financed: "1855.00" },
    status: "Pending",
  },
  {
    patient: {
      image: "/assets/images/Pedro.png",
      name: "Pedro Becker",
      clinic: "Smiling Teeth Clinic",
    },
    planType: "Membership",
    paymentDate: "May 1,2022",
    balance: { amount: "545.00", installments: "4" },
    paymentAmount: { amount: "25.00", financed: "1855.00" },
    status: "Pending",
  },
  {
    patient: {
      image: "/assets/images/Pedro.png",
      name: "Pedro Becker",
      clinic: "Smiling Teeth Clinic",
    },
    planType: "Membership",
    paymentDate: "May 1,2022",
    balance: { amount: "545.00", installments: "4" },
    paymentAmount: { amount: "25.00", financed: "1855.00" },
    status: "Active",
  },
  {
    patient: {
      image: "/assets/images/Pedro.png",
      name: "Pedro Becker",
      clinic: "Smiling Teeth Clinic",
    },
    planType: "Membership",
    paymentDate: "May 1,2022",
    balance: { amount: "545.00", installments: "4" },
    paymentAmount: { amount: "25.00", financed: "1855.00" },
    status: "Active",
  },
  {
    patient: {
      image: "/assets/images/Pedro.png",
      name: "Pedro Becker",
      clinic: "Smiling Teeth Clinic",
    },
    planType: "Membership",
    paymentDate: "May 1,2022",
    balance: { amount: "545.00", installments: "4" },
    paymentAmount: { amount: "25.00", financed: "1855.00" },
    status: "Active",
  },
  {
    patient: {
      image: "/assets/images/Pedro.png",
      name: "Pedro Becker",
      clinic: "Smiling Teeth Clinic",
    },
    planType: "Membership",
    paymentDate: "May 1,2022",
    balance: { amount: "545.00", installments: "4" },
    paymentAmount: { amount: "25.00", financed: "1855.00" },
    status: "Pending",
  },
  {
    patient: {
      image: "/assets/images/Pedro.png",
      name: "Pedro Becker",
      clinic: "Smiling Teeth Clinic",
    },
    planType: "Membership",
    paymentDate: "May 1,2022",
    balance: { amount: "545.00", installments: "4" },
    paymentAmount: { amount: "25.00", financed: "1855.00" },
    status: "Pending",
  },
  {
    patient: {
      image: "/assets/images/Pedro.png",
      name: "Pedro Becker",
      clinic: "Smiling Teeth Clinic",
    },
    planType: "Membership",
    paymentDate: "May 1,2022",
    balance: { amount: "545.00", installments: "4" },
    paymentAmount: { amount: "25.00", financed: "1855.00" },
    status: "Pending",
  },
  {
    patient: {
      image: "/assets/images/Pedro.png",
      name: "Pedro Becker",
      clinic: "Smiling Teeth Clinic",
    },
    planType: "Membership",
    paymentDate: "May 1,2022",
    balance: { amount: "545.00", installments: "4" },
    paymentAmount: { amount: "25.00", financed: "1855.00" },
    status: "Pending",
  },
];
